### PR TITLE
Update Ogone.pm

### PR DESCRIPTION
**Pull request by fayland**
fix typo

### CODE REVIEW

**Comment by timesselens** [comment]
Hi, thanks for typo fixes, any reason the pull request got closed?

**Comment by fayland** [comment]
I only want to fix the 'authorization only' issue in POD but the github web editor got the regex messed up too. :) so I just close it.

**Comment by fayland** [comment]
@timesselens do you have a sample code for VOID (DES) and REFUND (RFD)?

Thanks

**Comment by timesselens** [comment]
Took the patch and edited out the regex, applied changes and pushed.

@fayland have a look at the testcases (it's commented out though)

**Comment by fayland** [comment]
better fix 'Post Authorize' around L609 too. Thanks

**Comment by timesselens** [comment]
done, thanks!

**Comment by fayland** [comment]
again. :)

@timesselens do you have a sample code for VOID (DES) and REFUND (RFD)?

Thanks

**Comment by timesselens** [comment]
@fayland in the testcases 20_account.t L209

**Pull request closed without merging**
